#!/bin/bash
echo "ALX">>bash/alx
ls
cd ..
clear
cd bash
$ cd ..
cd ~
echo -e #!/bin/bashnecho ALX
#!/bin/bash
echo "ALX School is so cool"
- e #!/bin/bash\necho "ALX" 
#!/bin/bash
echo "ALX School is so cool" 
#!/bin/bash
echo "ALX School is so cool" 
